from __future__ import annotations

import sys
import unittest
from pathlib import Path
from types import SimpleNamespace
from unittest import mock


SCRIPT_DIR = Path(__file__).resolve().parents[1] / "scripts"
sys.path.insert(0, str(SCRIPT_DIR))

import gmr_main  # noqa: E402


class ResolveMrTargetTests(unittest.TestCase):
    def test_resolve_mr_target_from_url(self) -> None:
        resolved = gmr_main.resolve_mr_target(
            "https://gitlab.example.com/group/sub/project/-/merge_requests/42",
            None,
            None,
        )

        self.assertEqual(resolved["hostname"], "gitlab.example.com")
        self.assertEqual(resolved["repo"], "group/sub/project")
        self.assertEqual(resolved["iid"], "42")
        self.assertEqual(resolved["repo_encoded"], "group%2Fsub%2Fproject")

    def test_resolve_mr_target_uses_inferred_repo_context_for_iid(self) -> None:
        with mock.patch.object(
            gmr_main,
            "infer_repo_context",
            return_value=("gitlab.example.com", "group/sub/project"),
        ):
            resolved = gmr_main.resolve_mr_target("42", None, None)

        self.assertEqual(resolved["hostname"], "gitlab.example.com")
        self.assertEqual(resolved["repo"], "group/sub/project")
        self.assertEqual(resolved["mr_url"], "https://gitlab.example.com/group/sub/project/-/merge_requests/42")


class TraceExtractionTests(unittest.TestCase):
    def test_extract_failure_excerpt_prefers_error_lines_and_strips_noise(self) -> None:
        trace = """
section_start:123:foo
\x1b[31mERROR: Job failed: exit status 1\x1b[0m
$ echo -e "section_end:123:foo"
[!] Codeowners consistency check failed with error:
[NO_OWNERS] No owners found for changed file AGENTS.md
"""

        excerpt = gmr_main.extract_failure_excerpt(trace, 4)

        self.assertEqual(
            excerpt,
            [
                "[!] Codeowners consistency check failed with error:",
                "[NO_OWNERS] No owners found for changed file AGENTS.md",
            ],
        )

    def test_extract_failure_excerpt_prefers_semantic_failure_over_shell_and_generic_exit(self) -> None:
        trace = """
$ if ! xcode-select -p >/dev/null 2>&1; then sudo xcode-select -s /Applications/Xcode.app/Contents/Developer; fi
xcode-select: note: No developer tools were found, requesting install.
Generated by Danger Swift
Danger: Merge request description does not match the required template.
Please update the MR description before merge.
ERROR: Job failed: exit status 1
"""

        excerpt = gmr_main.extract_failure_excerpt(trace, 4)

        self.assertEqual(
            excerpt,
            [
                "Danger: Merge request description does not match the required template.",
                "Please update the MR description before merge.",
            ],
        )


class ManualJobTests(unittest.TestCase):
    def test_find_manual_job_by_name(self) -> None:
        status_payload = {
            "head_pipeline": {"id": 100},
            "manual_jobs": [
                {"id": 11, "name": "deploy-staging"},
                {"id": 12, "name": "publish-docs"},
            ],
        }
        with mock.patch.object(gmr_main, "resolve_mr_target", return_value={"repo": "group/project"}), mock.patch.object(
            gmr_main, "gather_status", return_value=status_payload
        ):
            ctx, pipeline, job = gmr_main.find_manual_job(
                "https://gitlab.example.com/group/project/-/merge_requests/42",
                None,
                None,
                "publish-docs",
            )

        self.assertEqual(ctx["repo"], "group/project")
        self.assertEqual(pipeline["id"], 100)
        self.assertEqual(job["id"], 12)

    def test_find_manual_job_raises_on_ambiguous_name(self) -> None:
        status_payload = {
            "head_pipeline": {"id": 100},
            "manual_jobs": [
                {"id": 11, "name": "deploy"},
                {"id": 12, "name": "deploy"},
            ],
        }
        with mock.patch.object(gmr_main, "resolve_mr_target", return_value={"repo": "group/project"}), mock.patch.object(
            gmr_main, "gather_status", return_value=status_payload
        ):
            with self.assertRaisesRegex(gmr_main.CommandError, "ambiguous"):
                gmr_main.find_manual_job("42", "group/project", "gitlab.example.com", "deploy")


class BotFilteringTests(unittest.TestCase):
    def test_get_unresolved_discussions_filters_bot_noise_by_default(self) -> None:
        discussions = [
            {
                "id": "bot-only",
                "resolved": False,
                "individual_note": False,
                "notes": [
                    {
                        "id": 1,
                        "system": False,
                        "resolvable": True,
                        "resolved": False,
                        "body": "Generated by Danger Swift",
                        "author": {"username": "group_123_bot_deadbeef"},
                    }
                ],
            },
            {
                "id": "human",
                "resolved": False,
                "individual_note": False,
                "notes": [
                    {
                        "id": 2,
                        "system": False,
                        "resolvable": True,
                        "resolved": False,
                        "body": "Please rename this API before merge.",
                        "author": {"username": "alice"},
                    }
                ],
            },
        ]
        with mock.patch.object(gmr_main, "glab_json", return_value=discussions):
            filtered = gmr_main.get_unresolved_discussions({"hostname": "gitlab.example.com", "repo_encoded": "x", "iid": "1"})
            full = gmr_main.get_unresolved_discussions(
                {"hostname": "gitlab.example.com", "repo_encoded": "x", "iid": "1"},
                include_bots=True,
            )

        self.assertEqual([item["id"] for item in filtered], ["human"])
        self.assertEqual([item["id"] for item in full], ["bot-only", "human"])


class AuthEnsureMrTests(unittest.TestCase):
    def test_command_auth_ensure_mr_uses_resolved_hostname(self) -> None:
        args = SimpleNamespace(target="42", repo="group/project", hostname="gitlab.example.com")
        with mock.patch.object(
            gmr_main,
            "resolve_mr_target",
            return_value={"hostname": "gitlab.example.com", "repo": "group/project", "iid": "42"},
        ), mock.patch.object(gmr_main.subprocess, "run") as run_mock:
            gmr_main.command_auth_ensure_mr(args)

        call_args = run_mock.call_args[0][0]
        self.assertTrue(call_args[0].endswith("ensure-glab-auth.sh"))
        self.assertEqual(call_args[1], "gitlab.example.com")


class CurrentUserResolutionTests(unittest.TestCase):
    def test_resolve_current_username_prefers_authenticated_username_matching_git_localpart(self) -> None:
        with mock.patch.object(
            gmr_main,
            "get_git_email_candidates",
            return_value=["oparin@me.com"],
        ), mock.patch.object(
            gmr_main,
            "get_authenticated_user",
            return_value={
                "username": "oparin.ivan3",
                "email": "oparin.ivan3@wb.ru",
                "public_email": "oparin.ivan3@wb.ru",
                "commit_email": "oparin.ivan3@wb.ru",
            },
        ):
            username = gmr_main.resolve_current_username("gitlab.example.com")

        self.assertEqual(username, "oparin.ivan3")

    def test_resolve_current_user_keeps_repo_local_email_ahead_of_global(self) -> None:
        with mock.patch.object(
            gmr_main,
            "run_command",
            side_effect=[
                "oparin.ivan3@wb.ru\n",
                gmr_main.CommandError("no worktree config"),
                "oparin.ivan3@wb.ru\n",
                "oparin@me.com\n",
            ],
        ):
            emails = gmr_main.get_git_email_candidates()

        self.assertEqual(emails, ["oparin.ivan3@wb.ru", "oparin@me.com"])

    def test_resolve_current_user_returns_alias_candidates(self) -> None:
        with mock.patch.object(
            gmr_main,
            "get_git_email_candidates",
            return_value=["oparin@me.com"],
        ), mock.patch.object(
            gmr_main,
            "get_authenticated_user",
            return_value={
                "username": "oparin.ivan3",
                "email": "oparin.ivan3@wb.ru",
                "public_email": "oparin.ivan3@wb.ru",
                "commit_email": "oparin.ivan3@wb.ru",
            },
        ):
            current_user = gmr_main.resolve_current_user("gitlab.example.com")

        self.assertEqual(current_user["username"], "oparin.ivan3")
        self.assertEqual(
            current_user["candidates"],
            ["oparin.ivan3", "oparin"],
        )


class WriteWrapperTests(unittest.TestCase):
    def test_command_mr_create_requires_fill_or_title(self) -> None:
        args = SimpleNamespace(
            repo="group/project",
            hostname="gitlab.example.com",
            source_branch="feature/test",
            target_branch=None,
            title=None,
            description=None,
            fill=False,
            fill_commit_body=False,
            draft=False,
            label=None,
            reviewer=None,
            assignee=None,
        )
        with mock.patch.object(
            gmr_main,
            "resolve_repo_target",
            return_value={"hostname": "gitlab.example.com", "repo": "group/project", "repo_encoded": "group%2Fproject"},
        ):
            with self.assertRaisesRegex(gmr_main.CommandError, "--fill or provide --title"):
                gmr_main.command_mr_create(args)

    def test_command_mr_create_builds_non_interactive_fill_command(self) -> None:
        args = SimpleNamespace(
            repo="group/project",
            hostname="gitlab.example.com",
            source_branch=None,
            target_branch="develop",
            title=None,
            description=None,
            fill=True,
            fill_commit_body=True,
            draft=True,
            label=["docs"],
            reviewer=["alice"],
            assignee=["bob"],
        )
        with mock.patch.object(
            gmr_main,
            "resolve_repo_target",
            return_value={"hostname": "gitlab.example.com", "repo": "group/project", "repo_encoded": "group%2Fproject"},
        ), mock.patch.object(
            gmr_main, "infer_current_branch", return_value="feature/test"
        ), mock.patch.object(
            gmr_main, "run_command", return_value="https://gitlab.example.com/group/project/-/merge_requests/42"
        ) as run_mock, mock.patch.object(
            gmr_main,
            "get_mr",
            return_value={
                "iid": 42,
                "title": "Feature test",
                "description": "",
                "state": "opened",
                "draft": True,
                "web_url": "https://gitlab.example.com/group/project/-/merge_requests/42",
                "source_branch": "feature/test",
                "target_branch": "develop",
            },
        ), mock.patch.object(gmr_main, "print_json") as print_mock:
            gmr_main.command_mr_create(args)

        command = run_mock.call_args.args[0]
        env = run_mock.call_args.kwargs["env"]
        self.assertEqual(
            command,
            [
                "glab",
                "mr",
                "create",
                "-R",
                "group/project",
                "-s",
                "feature/test",
                "--yes",
                "--fill",
                "--fill-commit-body",
                "-b",
                "develop",
                "--draft",
                "-l",
                "docs",
                "--reviewer",
                "alice",
                "-a",
                "bob",
            ],
        )
        self.assertEqual(env["GITLAB_HOST"], "gitlab.example.com")
        payload = print_mock.call_args.args[0]
        self.assertEqual(payload["mr_url"], "https://gitlab.example.com/group/project/-/merge_requests/42")
        self.assertEqual(payload["target"]["iid"], "42")
        self.assertEqual(payload["mr"]["iid"], 42)
        self.assertEqual(payload["mr"]["title"], "Feature test")
        self.assertEqual(payload["mr"]["description"], "")
        self.assertEqual(payload["mr"]["source_branch"], "feature/test")
        self.assertEqual(payload["mr"]["target_branch"], "develop")
        self.assertTrue(payload["mr"]["draft"])

    def test_command_mr_create_with_explicit_fields_returns_post_fetched_payload(self) -> None:
        args = SimpleNamespace(
            repo="group/project",
            hostname="gitlab.example.com",
            source_branch="feature/test",
            target_branch="main",
            title="Feature title",
            description="Explicit description",
            fill=False,
            fill_commit_body=False,
            draft=False,
            label=None,
            reviewer=None,
            assignee=None,
        )
        with mock.patch.object(
            gmr_main,
            "resolve_repo_target",
            return_value={"hostname": "gitlab.example.com", "repo": "group/project", "repo_encoded": "group%2Fproject"},
        ), mock.patch.object(
            gmr_main,
            "run_command",
            return_value="https://gitlab.example.com/group/project/-/merge_requests/43",
        ) as run_mock, mock.patch.object(
            gmr_main,
            "get_mr",
            return_value={
                "iid": 43,
                "title": "Feature title",
                "description": "Explicit description",
                "state": "opened",
                "draft": False,
                "web_url": "https://gitlab.example.com/group/project/-/merge_requests/43",
                "source_branch": "feature/test",
                "target_branch": "main",
            },
        ), mock.patch.object(gmr_main, "print_json") as print_mock:
            gmr_main.command_mr_create(args)

        self.assertEqual(
            run_mock.call_args.args[0],
            [
                "glab",
                "mr",
                "create",
                "-R",
                "group/project",
                "-s",
                "feature/test",
                "--yes",
                "-t",
                "Feature title",
                "-d",
                "Explicit description",
                "-b",
                "main",
            ],
        )
        payload = print_mock.call_args.args[0]
        self.assertEqual(payload["mr"]["iid"], 43)
        self.assertEqual(payload["mr"]["title"], "Feature title")
        self.assertEqual(payload["mr"]["description"], "Explicit description")
        self.assertEqual(payload["mr"]["source_branch"], "feature/test")
        self.assertEqual(payload["mr"]["target_branch"], "main")
        self.assertFalse(payload["mr"]["draft"])

    def test_command_mr_list_builds_mine_author_filter(self) -> None:
        args = SimpleNamespace(
            repo="group/project",
            hostname="gitlab.example.com",
            state="opened",
            author=None,
            assignee=None,
            reviewer=None,
            mine=True,
            mine_role="author",
            draft=False,
            not_draft=False,
            source_branch=None,
            target_branch=None,
            search=None,
            label=None,
            page=1,
            per_page=30,
        )
        mr_list = [
            {
                "iid": 42,
                "title": "Example MR",
                "state": "opened",
                "draft": False,
                "detailed_merge_status": "mergeable",
                "author": {"username": "oparin.ivan3"},
                "assignee": {"username": "oparin.ivan3"},
                "assignees": [{"username": "oparin.ivan3"}],
                "reviewers": [{"username": "alice"}],
                "source_branch": "feature/test",
                "target_branch": "develop",
                "labels": ["docs"],
                "updated_at": "2026-04-01T00:00:00Z",
                "web_url": "https://gitlab.example.com/group/project/-/merge_requests/42",
            }
        ]
        with mock.patch.object(
            gmr_main,
            "resolve_repo_target",
            return_value={"hostname": "gitlab.example.com", "repo": "group/project", "repo_encoded": "group%2Fproject"},
        ), mock.patch.object(
            gmr_main,
            "resolve_current_user",
            return_value={
                "username": "oparin.ivan3",
                "candidates": ["oparin.ivan3", "oparin"],
                "git_emails": ["oparin.ivan3@wb.ru"],
                "git_localparts": ["oparin.ivan3"],
                "authenticated_username": "oparin.ivan3",
            },
        ), mock.patch.object(
            gmr_main, "run_command", return_value=gmr_main.json.dumps(mr_list)
        ) as run_mock, mock.patch.object(gmr_main, "print_json") as print_mock:
            gmr_main.command_mr_list(args)

        command = run_mock.call_args.args[0]
        env = run_mock.call_args.kwargs["env"]
        self.assertIn("--author", command)
        self.assertIn("oparin.ivan3", command)
        self.assertEqual(env["GITLAB_HOST"], "gitlab.example.com")
        self.assertEqual(print_mock.call_args.args[0]["filters"]["current_user"], "oparin.ivan3")
        self.assertEqual(
            print_mock.call_args.args[0]["filters"]["current_user_candidates"],
            ["oparin.ivan3", "oparin"],
        )
        self.assertEqual(print_mock.call_args.args[0]["count"], 1)

    def test_command_mr_list_post_filters_mine_results_by_alias_candidates(self) -> None:
        args = SimpleNamespace(
            repo="group/project",
            hostname="gitlab.example.com",
            state="opened",
            author=None,
            assignee=None,
            reviewer=None,
            mine=True,
            mine_role="author",
            draft=False,
            not_draft=False,
            source_branch=None,
            target_branch=None,
            search=None,
            label=None,
            page=1,
            per_page=30,
        )
        mr_list = [
            {
                "iid": 42,
                "title": "Mine via git localpart",
                "state": "opened",
                "draft": False,
                "detailed_merge_status": "mergeable",
                "author": {"username": "oparin"},
                "assignee": {"username": "oparin"},
                "assignees": [{"username": "oparin"}],
                "reviewers": [],
                "source_branch": "feature/mine",
                "target_branch": "develop",
                "labels": [],
                "updated_at": "2026-04-01T00:00:00Z",
                "web_url": "https://gitlab.example.com/group/project/-/merge_requests/42",
            },
            {
                "iid": 43,
                "title": "Someone else's MR",
                "state": "opened",
                "draft": False,
                "detailed_merge_status": "mergeable",
                "author": {"username": "alice"},
                "assignee": {"username": "alice"},
                "assignees": [{"username": "alice"}],
                "reviewers": [],
                "source_branch": "feature/other",
                "target_branch": "develop",
                "labels": [],
                "updated_at": "2026-04-01T00:00:00Z",
                "web_url": "https://gitlab.example.com/group/project/-/merge_requests/43",
            },
        ]
        with mock.patch.object(
            gmr_main,
            "resolve_repo_target",
            return_value={"hostname": "gitlab.example.com", "repo": "group/project", "repo_encoded": "group%2Fproject"},
        ), mock.patch.object(
            gmr_main,
            "resolve_current_user",
            return_value={
                "username": "oparin.ivan3",
                "candidates": ["oparin.ivan3", "oparin"],
                "git_emails": ["oparin@me.com"],
                "git_localparts": ["oparin"],
                "authenticated_username": "oparin.ivan3",
            },
        ), mock.patch.object(
            gmr_main, "run_command", return_value=gmr_main.json.dumps(mr_list)
        ), mock.patch.object(gmr_main, "print_json") as print_mock:
            gmr_main.command_mr_list(args)

        payload = print_mock.call_args.args[0]
        self.assertEqual(payload["count"], 1)
        self.assertEqual([item["iid"] for item in payload["items"]], [42])

    def test_command_mr_list_rejects_draft_flag_conflict(self) -> None:
        args = SimpleNamespace(
            repo="group/project",
            hostname="gitlab.example.com",
            state="opened",
            author=None,
            assignee=None,
            reviewer=None,
            mine=False,
            mine_role="author",
            draft=True,
            not_draft=True,
            source_branch=None,
            target_branch=None,
            search=None,
            label=None,
            page=1,
            per_page=30,
        )
        with mock.patch.object(
            gmr_main,
            "resolve_repo_target",
            return_value={"hostname": "gitlab.example.com", "repo": "group/project", "repo_encoded": "group%2Fproject"},
        ):
            with self.assertRaisesRegex(gmr_main.CommandError, "--draft and --not-draft"):
                gmr_main.command_mr_list(args)

    def test_command_mr_approve_uses_resolved_sha_and_host_env(self) -> None:
        args = SimpleNamespace(target="42", repo="group/project", hostname="gitlab.example.com", sha=None)
        with mock.patch.object(
            gmr_main,
            "resolve_mr_target",
            return_value={"hostname": "gitlab.example.com", "repo": "group/project", "iid": "42"},
        ), mock.patch.object(gmr_main, "get_mr", return_value={"sha": "deadbeef"}), mock.patch.object(
            gmr_main, "run_command", return_value="approved"
        ) as run_mock, mock.patch.object(gmr_main, "print_json") as print_mock:
            gmr_main.command_mr_approve(args)

        command = run_mock.call_args.args[0]
        env = run_mock.call_args.kwargs["env"]
        self.assertEqual(command, ["glab", "mr", "approve", "42", "-R", "group/project", "-s", "deadbeef"])
        self.assertEqual(env["GITLAB_HOST"], "gitlab.example.com")
        self.assertEqual(print_mock.call_args.args[0]["sha"], "deadbeef")

    def test_command_mr_merge_refuses_failed_pipeline(self) -> None:
        args = SimpleNamespace(
            target="42",
            repo="group/project",
            hostname="gitlab.example.com",
            sha=None,
            auto_merge=False,
            keep_source_branch=False,
            rebase=False,
            squash=False,
            message=None,
        )
        with mock.patch.object(
            gmr_main,
            "resolve_mr_target",
            return_value={"hostname": "gitlab.example.com", "repo": "group/project", "iid": "42"},
        ), mock.patch.object(
            gmr_main,
            "get_mr",
            return_value={"sha": "deadbeef", "draft": False, "head_pipeline": {"status": "failed"}},
        ):
            with self.assertRaisesRegex(gmr_main.CommandError, "failed"):
                gmr_main.command_mr_merge(args)

    def test_command_mr_merge_invokes_safe_glab_command(self) -> None:
        args = SimpleNamespace(
            target="42",
            repo="group/project",
            hostname="gitlab.example.com",
            sha=None,
            auto_merge=True,
            keep_source_branch=False,
            rebase=False,
            squash=False,
            message=None,
        )
        with mock.patch.object(
            gmr_main,
            "resolve_mr_target",
            return_value={"hostname": "gitlab.example.com", "repo": "group/project", "iid": "42"},
        ), mock.patch.object(
            gmr_main,
            "get_mr",
            return_value={"sha": "deadbeef", "draft": False, "head_pipeline": {"status": "running"}},
        ), mock.patch.object(
            gmr_main, "run_command", return_value="merged"
        ) as run_mock, mock.patch.object(gmr_main, "print_json") as print_mock:
            gmr_main.command_mr_merge(args)

        command = run_mock.call_args.args[0]
        env = run_mock.call_args.kwargs["env"]
        self.assertIn("--auto-merge", command)
        self.assertIn("--remove-source-branch", command)
        self.assertEqual(env["GITLAB_HOST"], "gitlab.example.com")
        self.assertEqual(print_mock.call_args.args[0]["action"], "merge")


if __name__ == "__main__":
    unittest.main()
