#!/usr/bin/env python3
from __future__ import annotations

import argparse
import getpass
import json
import os
import re
import shutil
import subprocess
import sys
import urllib.parse
from pathlib import Path
from typing import Any

# CLI/API split is deliberate:
# - Read operations (get_mr, pipelines, jobs, traces, discussions) use `glab api`
#   for structured JSON responses with explicit hostname control.
# - Write and list operations (mr list, create, approve, merge) use `glab mr` CLI
#   subcommands for built-in repo resolution, flag composition, and auth handling.

ANSI_ESCAPE_RE = re.compile(r"\x1B\[[0-?]*[ -/]*[@-~]")
MR_URL_RE = re.compile(
    r"^(?:(?P<scheme>https?)://)?(?P<host>[^/]+)/(?P<repo>.+)/-/merge_requests/(?P<iid>\d+)/?$"
)
ERROR_LINE_RE = re.compile(
    r"(\[!\]|\berror\b|\bfailed\b|\bexception\b|\btraceback\b|\bfatal\b|\bno owners found\b|\bnot found\b)",
    re.IGNORECASE,
)
GENERIC_JOB_FAILURE_RE = re.compile(r"^ERROR:\s+Job failed:\s+exit status\s+\d+\s*$", re.IGNORECASE)
SHELL_COMMAND_RE = re.compile(r"^\$\s+")
SHELL_IF_COMMAND_RE = re.compile(r"^\$\s+if\s+!", re.IGNORECASE)
SEMANTIC_FAILURE_RE = re.compile(
    r"(\bdanger\b|\bfastlane\b|\bxcodebuild\b|\bswiftlint\b|\beslint\b|\bktlint\b|\bdetekt\b|"
    r"\bclang-tidy\b|\bcodeowners\b|\btemplate\b|\bdescription\b|\blint\b|\btest(?:s)?\b)",
    re.IGNORECASE,
)
BOT_AUTHOR_RE = re.compile(r"(^|[_-])bot([_-]|$)", re.IGNORECASE)
MR_WEB_URL_RE = re.compile(r"https?://\S+/-/merge_requests/\d+")
BOT_BODY_MARKERS = (
    "generated by",
    "danger swift",
    "a review request will be placed here",
    "metadata=\"generated_by_",
    "danger-id-",
)
MINE_ALIASES = {"@me", "me", "mine", "@mine"}


class CommandError(RuntimeError):
    pass


def run_command(
    args: list[str],
    *,
    capture_output: bool = True,
    env: dict[str, str] | None = None,
    input_text: str | None = None,
) -> str:
    completed = subprocess.run(
        args,
        text=True,
        input=input_text,
        capture_output=capture_output,
        env=env,
    )
    if completed.returncode != 0:
        stderr = (completed.stderr or "").strip()
        stdout = (completed.stdout or "").strip()
        detail = stderr or stdout or f"exit code {completed.returncode}"
        raise CommandError(f"{' '.join(args)} failed: {detail}")
    return completed.stdout if capture_output else ""


def print_json(payload: Any) -> None:
    print(json.dumps(payload, ensure_ascii=False, indent=2))


def strip_ansi(text: str) -> str:
    return ANSI_ESCAPE_RE.sub("", text)


def shorten(text: str, limit: int) -> str:
    compact = " ".join(text.split())
    if len(compact) <= limit:
        return compact
    return compact[: limit - 1].rstrip() + "…"


def unique_strings(values: list[str | None]) -> list[str]:
    seen: set[str] = set()
    results: list[str] = []
    for value in values:
        if not value:
            continue
        cleaned = value.strip()
        if not cleaned:
            continue
        key = cleaned.lower()
        if key in seen:
            continue
        seen.add(key)
        results.append(cleaned)
    return results


def email_localparts(emails: list[str | None]) -> list[str]:
    localparts: list[str | None] = []
    for email in emails:
        if not email or "@" not in email:
            continue
        localparts.append(email.split("@", 1)[0].strip())
    return unique_strings(localparts)


def clean_trace_lines(text: str) -> list[str]:
    lines: list[str] = []
    for raw_line in strip_ansi(text).splitlines():
        line = raw_line.strip()
        if not line:
            continue
        if line.startswith("section_start:") or line.startswith("section_end:"):
            continue
        if line.startswith("$ echo -e "):
            continue
        lines.append(line)
    return lines


def score_trace_line(line: str) -> int:
    score = 0
    lowered = line.lower()

    if SHELL_IF_COMMAND_RE.match(line):
        score -= 80
    elif SHELL_COMMAND_RE.match(line):
        score -= 30

    if GENERIC_JOB_FAILURE_RE.match(line):
        score -= 60

    if ERROR_LINE_RE.search(line):
        score += 30
    if SEMANTIC_FAILURE_RE.search(line) and not SHELL_COMMAND_RE.match(line):
        score += 80
    if "danger" in lowered and ("template" in lowered or "description" in lowered):
        score += 60
    if "generated by danger" in lowered:
        score -= 40
    if "job failed" in lowered and "exit status" in lowered:
        score -= 20
    return score


def extract_failure_excerpt(trace: str, limit: int) -> list[str]:
    lines = clean_trace_lines(trace)
    if not lines:
        return []

    scored_lines = [(index, score_trace_line(line), line) for index, line in enumerate(lines)]
    positive_scored_lines = [item for item in scored_lines if item[1] > 0]
    if not positive_scored_lines:
        source = lines[-max(limit, 12) :]
    else:
        best_index, _, _ = max(positive_scored_lines, key=lambda item: (item[1], item[0]))
        source = []
        for _, score, line in scored_lines[best_index:]:
            if score <= 0 and source:
                break
            if score <= 0 and not source:
                continue
            source.append(line)
            if len(source) >= limit:
                break
        if not source:
            source = [lines[best_index]]

    excerpt: list[str] = []
    seen: set[str] = set()
    for line in source:
        if line in seen:
            continue
        seen.add(line)
        excerpt.append(line)
    return excerpt


def encode_repo(repo: str) -> str:
    return urllib.parse.quote(repo, safe="")


def glab_json(hostname: str, endpoint: str, *, method: str = "GET", fields: dict[str, str] | None = None) -> Any:
    cmd = ["glab", "api", "--hostname", hostname]
    if method != "GET":
        cmd += ["-X", method]
    if fields:
        for key, value in fields.items():
            cmd += ["-f", f"{key}={value}"]
    cmd.append(endpoint)
    output = run_command(cmd)
    if not output.strip():
        return None
    return json.loads(output)


def glab_cli_env(hostname: str) -> dict[str, str]:
    env = os.environ.copy()
    env["GITLAB_HOST"] = hostname
    return env


def extract_mr_web_url(text: str) -> str | None:
    match = MR_WEB_URL_RE.search(text)
    return match.group(0) if match else None


def parse_target_host(target: str) -> dict[str, str | None]:
    """Return hostname and authority (host:port when port is present) from a target."""
    raw = target.strip()
    if not raw:
        raise CommandError("Empty hostname or URL.")
    if "://" in raw:
        parsed = urllib.parse.urlparse(raw)
        if not parsed.hostname:
            raise CommandError(f"Could not parse a hostname from: {raw}")
        authority = f"{parsed.hostname}:{parsed.port}" if parsed.port else None
        return {"hostname": parsed.hostname, "authority": authority}
    cleaned = raw
    if "@" in cleaned:
        cleaned = cleaned.split("@", 1)[1]
    cleaned = cleaned.split("/", 1)[0]
    if ":" in cleaned:
        hostname = cleaned.split(":", 1)[0]
        if not hostname:
            raise CommandError(f"Could not parse a hostname from: {raw}")
        return {"hostname": hostname, "authority": cleaned}
    if not cleaned:
        raise CommandError(f"Could not parse a hostname from: {raw}")
    return {"hostname": cleaned, "authority": None}


def parse_target_hostname(target: str) -> str:
    return parse_target_host(target)["hostname"]


def parse_git_remote(remote: str) -> tuple[str, str]:
    remote = remote.strip()
    if "://" in remote:
        parsed = urllib.parse.urlparse(remote)
        if not parsed.hostname or not parsed.path:
            raise CommandError(f"Unsupported git remote: {remote}")
        host = parsed.hostname
        if parsed.port:
            host = f"{host}:{parsed.port}"
        repo = parsed.path.lstrip("/")
    else:
        cleaned = remote
        if "@" in cleaned:
            cleaned = cleaned.split("@", 1)[1]
        if ":" not in cleaned:
            raise CommandError(f"Unsupported git remote: {remote}")
        host, repo = cleaned.split(":", 1)

    repo = repo.removesuffix(".git").strip("/")
    if not host or not repo:
        raise CommandError(f"Unsupported git remote: {remote}")
    return host, repo


def infer_repo_context() -> tuple[str, str] | None:
    try:
        remote = run_command(["git", "remote", "get-url", "origin"]).strip()
    except CommandError:
        return None
    return parse_git_remote(remote)


def infer_current_branch() -> str | None:
    try:
        branch = run_command(["git", "rev-parse", "--abbrev-ref", "HEAD"]).strip()
    except CommandError:
        return None
    if not branch or branch == "HEAD":
        return None
    return branch


def get_git_email_candidates() -> list[str]:
    candidates: list[str] = []
    for command in (
        ["git", "config", "--get", "--local", "user.email"],
        ["git", "config", "--get", "--worktree", "user.email"],
        ["git", "config", "--get", "user.email"],
        ["git", "config", "--get", "--global", "user.email"],
    ):
        try:
            email = run_command(command).strip()
        except CommandError:
            continue
        if email and email not in candidates:
            candidates.append(email)
    return candidates


def get_authenticated_user(hostname: str) -> dict[str, Any]:
    try:
        user = glab_json(hostname, "user")
    except CommandError:
        return {}
    return user if isinstance(user, dict) else {}


def get_authenticated_username(hostname: str) -> str | None:
    username = get_authenticated_user(hostname).get("username")
    return username.strip() if isinstance(username, str) and username.strip() else None


def resolve_current_user(hostname: str) -> dict[str, Any]:
    email_candidates = get_git_email_candidates()
    localparts = email_localparts(email_candidates)
    authenticated_user = get_authenticated_user(hostname)
    auth_username = (authenticated_user.get("username") or "").strip()
    auth_localparts = email_localparts(
        [
            authenticated_user.get("email"),
            authenticated_user.get("public_email"),
            authenticated_user.get("commit_email"),
        ]
    )

    current_user: str | None = None
    if auth_username:
        auth_username_key = auth_username.lower()
        localpart_keys = [localpart.lower() for localpart in localparts]
        if auth_username_key in localpart_keys or any(
            localpart and auth_username_key.startswith(localpart) for localpart in localpart_keys
        ):
            current_user = auth_username

    if not current_user and localparts:
        current_user = localparts[0]
    if not current_user and auth_username:
        current_user = auth_username
    if not current_user and auth_localparts:
        current_user = auth_localparts[0]

    if not current_user:
        raise CommandError(
            "Could not resolve the current username from git config or the authenticated GitLab account."
        )

    return {
        "username": current_user,
        "candidates": unique_strings([current_user, *localparts, *auth_localparts, auth_username]),
        "git_emails": email_candidates,
        "git_localparts": localparts,
        "authenticated_username": auth_username or None,
    }


def resolve_current_username(hostname: str) -> str:
    return resolve_current_user(hostname)["username"]


def resolve_user_filter(
    value: str | None,
    hostname: str,
    current_user: dict[str, Any] | None,
) -> tuple[str | None, list[str], dict[str, Any] | None]:
    if not value:
        return None, [], current_user
    if value.lower() in MINE_ALIASES:
        current_user = current_user or resolve_current_user(hostname)
        return current_user["username"], current_user["candidates"], current_user
    return value, [value], current_user


def resolve_repo_target(repo: str | None, hostname: str | None) -> dict[str, str]:
    resolved_repo = repo
    resolved_host = hostname
    if not resolved_repo or not resolved_host:
        inferred = infer_repo_context()
        if inferred:
            inferred_host, inferred_repo = inferred
            resolved_repo = resolved_repo or inferred_repo
            resolved_host = resolved_host or inferred_host

    if not resolved_repo:
        raise CommandError("Repository is required when it cannot be inferred from the current checkout.")
    if not resolved_host:
        raise CommandError("Hostname is required when it cannot be inferred from the current checkout.")

    return {
        "hostname": resolved_host,
        "repo": resolved_repo,
        "repo_encoded": encode_repo(resolved_repo),
    }


def resolve_mr_target(target: str, repo: str | None, hostname: str | None) -> dict[str, str]:
    match = MR_URL_RE.match(target)
    if match:
        resolved_host = match.group("host")
        resolved_repo = match.group("repo").strip("/")
        return {
            "hostname": resolved_host,
            "repo": resolved_repo,
            "repo_encoded": encode_repo(resolved_repo),
            "iid": match.group("iid"),
            "mr_url": (
                f"https://{resolved_host}/{resolved_repo}/-/merge_requests/{match.group('iid')}"
                if not match.group("scheme")
                else target.rstrip("/")
            ),
        }

    if not target.isdigit():
        raise CommandError(
            "MR target must be a full merge request URL or a numeric IID with --repo."
        )

    repo_target = resolve_repo_target(repo, hostname)

    return {
        "hostname": repo_target["hostname"],
        "repo": repo_target["repo"],
        "repo_encoded": repo_target["repo_encoded"],
        "iid": target,
        "mr_url": f"https://{repo_target['hostname']}/{repo_target['repo']}/-/merge_requests/{target}",
    }


def select_mr_fields(mr: dict[str, Any]) -> dict[str, Any]:
    return {
        "iid": mr.get("iid"),
        "title": mr.get("title"),
        "description": mr.get("description"),
        "state": mr.get("state"),
        "draft": mr.get("draft"),
        "merge_status": mr.get("merge_status"),
        "detailed_merge_status": mr.get("detailed_merge_status"),
        "web_url": mr.get("web_url"),
        "source_branch": mr.get("source_branch"),
        "target_branch": mr.get("target_branch"),
        "sha": mr.get("sha"),
        "updated_at": mr.get("updated_at"),
        "author": (mr.get("author") or {}).get("username") or (mr.get("author") or {}).get("name"),
    }


def select_pipeline_fields(pipeline: dict[str, Any] | None) -> dict[str, Any] | None:
    if not pipeline:
        return None
    return {
        "id": pipeline.get("id"),
        "status": pipeline.get("status"),
        "ref": pipeline.get("ref"),
        "sha": pipeline.get("sha"),
        "web_url": pipeline.get("web_url"),
        "created_at": pipeline.get("created_at"),
        "updated_at": pipeline.get("updated_at"),
    }


def select_job_fields(job: dict[str, Any]) -> dict[str, Any]:
    return {
        "id": job.get("id"),
        "name": job.get("name"),
        "stage": job.get("stage"),
        "status": job.get("status"),
        "allow_failure": job.get("allow_failure"),
        "web_url": job.get("web_url"),
        "started_at": job.get("started_at"),
        "finished_at": job.get("finished_at"),
    }


def summarize_users(users: list[dict[str, Any]] | None) -> list[str]:
    return [
        (user.get("username") or user.get("name") or "").strip()
        for user in (users or [])
        if (user.get("username") or user.get("name"))
    ]


def matches_any_user(username: str | None, candidates: list[str]) -> bool:
    if not username:
        return False
    username_key = username.strip().lower()
    if not username_key:
        return False
    return any(candidate and username_key == candidate.lower() for candidate in candidates)


def merge_request_matches_user_filter(mr: dict[str, Any], field: str, candidates: list[str]) -> bool:
    if not candidates:
        return True

    if field == "author":
        author = mr.get("author") or {}
        return matches_any_user(author.get("username") or author.get("name"), candidates)

    if field == "assignee":
        assignee = mr.get("assignee") or {}
        assignees = unique_strings(
            [
                assignee.get("username"),
                assignee.get("name"),
                *summarize_users(mr.get("assignees")),
            ]
        )
        return any(matches_any_user(username, candidates) for username in assignees)

    if field == "reviewer":
        reviewers = summarize_users(mr.get("reviewers"))
        return any(matches_any_user(username, candidates) for username in reviewers)

    raise ValueError(f"Unsupported user filter field: {field}")


# glab CLI server-side filtering by author/assignee/reviewer matches inconsistently
# across GitLab versions and self-hosted instances (display name vs username).
# Post-filter ensures consistent matching against all resolved username candidates,
# including @me/mine aliases that expand to multiple candidate strings.
def post_filter_merge_requests(
    merge_requests: list[dict[str, Any]],
    *,
    author_candidates: list[str],
    assignee_candidates: list[str],
    reviewer_candidates: list[str],
    draft: bool,
    not_draft: bool,
) -> list[dict[str, Any]]:
    filtered: list[dict[str, Any]] = []
    for mr in merge_requests:
        if not merge_request_matches_user_filter(mr, "author", author_candidates):
            continue
        if not merge_request_matches_user_filter(mr, "assignee", assignee_candidates):
            continue
        if not merge_request_matches_user_filter(mr, "reviewer", reviewer_candidates):
            continue

        is_draft = bool(mr.get("draft"))
        if draft and not is_draft:
            continue
        if not_draft and is_draft:
            continue

        filtered.append(mr)
    return filtered


def select_mr_list_fields(mr: dict[str, Any]) -> dict[str, Any]:
    assignee = mr.get("assignee") or {}
    return {
        "iid": mr.get("iid"),
        "title": mr.get("title"),
        "state": mr.get("state"),
        "draft": mr.get("draft"),
        "detailed_merge_status": mr.get("detailed_merge_status"),
        "author": ((mr.get("author") or {}).get("username") or (mr.get("author") or {}).get("name")),
        "assignee": assignee.get("username") or assignee.get("name"),
        "assignees": summarize_users(mr.get("assignees")),
        "reviewers": summarize_users(mr.get("reviewers")),
        "source_branch": mr.get("source_branch"),
        "target_branch": mr.get("target_branch"),
        "labels": mr.get("labels") or [],
        "updated_at": mr.get("updated_at"),
        "web_url": mr.get("web_url"),
    }


def get_mr(ctx: dict[str, str]) -> dict[str, Any]:
    return glab_json(
        ctx["hostname"],
        f"projects/{ctx['repo_encoded']}/merge_requests/{ctx['iid']}",
    )


def get_mr_pipelines(ctx: dict[str, str]) -> list[dict[str, Any]]:
    pipelines = glab_json(
        ctx["hostname"],
        f"projects/{ctx['repo_encoded']}/merge_requests/{ctx['iid']}/pipelines",
    )
    return pipelines or []


def get_pipeline_jobs(ctx: dict[str, str], pipeline_id: int | str) -> list[dict[str, Any]]:
    jobs = glab_json(
        ctx["hostname"],
        f"projects/{ctx['repo_encoded']}/pipelines/{pipeline_id}/jobs?per_page=100",
    )
    return jobs or []


def get_job_trace(ctx: dict[str, str], job_id: int | str) -> str:
    return run_command(
        [
            "glab",
            "api",
            "--hostname",
            ctx["hostname"],
            f"projects/{ctx['repo_encoded']}/jobs/{job_id}/trace",
        ]
    )


def get_review_changes(ctx: dict[str, str]) -> tuple[list[dict[str, Any]], dict[str, Any]]:
    try:
        payload = glab_json(
            ctx["hostname"],
            f"projects/{ctx['repo_encoded']}/merge_requests/{ctx['iid']}/changes",
        )
        changes = payload.get("changes") or []
        files = [
            {
                "old_path": change.get("old_path"),
                "new_path": change.get("new_path"),
                "new_file": change.get("new_file"),
                "renamed_file": change.get("renamed_file"),
                "deleted_file": change.get("deleted_file"),
            }
            for change in changes
        ]
        meta = {
            "changes_count": payload.get("changes_count"),
            "overflow": payload.get("overflow"),
        }
        return files, meta
    except CommandError:
        diffs = glab_json(
            ctx["hostname"],
            f"projects/{ctx['repo_encoded']}/merge_requests/{ctx['iid']}/diffs?per_page=100",
        )
        files = [
            {
                "old_path": diff.get("old_path"),
                "new_path": diff.get("new_path"),
                "new_file": diff.get("new_file"),
                "renamed_file": diff.get("renamed_file"),
                "deleted_file": diff.get("deleted_file"),
            }
            for diff in (diffs or [])
        ]
        return files, {"changes_count": len(files), "overflow": None}


def note_author(note: dict[str, Any]) -> str:
    author = note.get("author") or {}
    return (author.get("username") or author.get("name") or "").strip()


def is_bot_noise_note(note: dict[str, Any]) -> bool:
    author = note_author(note)
    body = (note.get("body") or "").lower()
    if author and BOT_AUTHOR_RE.search(author):
        return True
    return any(marker in body for marker in BOT_BODY_MARKERS)


def get_unresolved_discussions(ctx: dict[str, str], *, include_bots: bool = False) -> list[dict[str, Any]]:
    discussions = glab_json(
        ctx["hostname"],
        f"projects/{ctx['repo_encoded']}/merge_requests/{ctx['iid']}/discussions?per_page=100",
    )
    results: list[dict[str, Any]] = []
    for discussion in discussions or []:
        resolved = bool(discussion.get("resolved"))
        notes = discussion.get("notes") or []
        non_system_notes = [note for note in notes if not note.get("system")]
        resolvable_notes = [note for note in non_system_notes if note.get("resolvable")]
        if not include_bots:
            resolvable_notes = [note for note in resolvable_notes if not is_bot_noise_note(note)]
        if resolved or not resolvable_notes:
            continue
        results.append(
            {
                "id": discussion.get("id"),
                "individual_note": discussion.get("individual_note"),
                "notes": [
                    {
                        "id": note.get("id"),
                        "author": note_author(note),
                        "body": shorten(note.get("body") or "", 400),
                        "created_at": note.get("created_at"),
                        "resolvable": note.get("resolvable"),
                        "resolved": note.get("resolved"),
                    }
                    for note in resolvable_notes
                ],
            }
        )
    return results


def gather_status(ctx: dict[str, str], trace_lines: int) -> dict[str, Any]:
    mr = get_mr(ctx)
    pipelines = get_mr_pipelines(ctx)
    head_pipeline = mr.get("head_pipeline") or (pipelines[0] if pipelines else None)
    jobs = get_pipeline_jobs(ctx, head_pipeline["id"]) if head_pipeline else []

    failed_jobs: list[dict[str, Any]] = []
    manual_jobs: list[dict[str, Any]] = []
    for job in jobs:
        selected = select_job_fields(job)
        if job.get("status") == "failed" and not job.get("allow_failure"):
            try:
                trace = get_job_trace(ctx, job["id"])
                selected["failure_excerpt"] = extract_failure_excerpt(trace, trace_lines)
            except CommandError as exc:
                selected["failure_excerpt"] = [f"Unable to fetch trace: {exc}"]
            failed_jobs.append(selected)
        elif job.get("status") == "manual":
            manual_jobs.append(selected)

    return {
        "target": ctx,
        "mr": select_mr_fields(mr),
        "head_pipeline": select_pipeline_fields(head_pipeline),
        "recent_pipelines": [select_pipeline_fields(pipeline) for pipeline in pipelines[:5]],
        "failed_jobs": failed_jobs,
        "manual_jobs": manual_jobs,
    }


def find_manual_job(mr_target: str, repo: str | None, hostname: str | None, identifier: str) -> tuple[dict[str, str], dict[str, Any], dict[str, Any]]:
    resolved = resolve_mr_target(mr_target, repo, hostname)
    status_payload = gather_status(resolved, trace_lines=8)
    head_pipeline = status_payload.get("head_pipeline")
    manual_jobs = status_payload.get("manual_jobs") or []
    if not head_pipeline:
        raise CommandError("The merge request does not have a head pipeline.")
    if not manual_jobs:
        raise CommandError("The head pipeline does not have manual jobs.")

    if identifier.isdigit():
        for job in manual_jobs:
            if str(job["id"]) == identifier:
                return resolved, head_pipeline, job
        raise CommandError(f"Manual job {identifier} was not found in the head pipeline.")

    matches = [job for job in manual_jobs if job["name"] == identifier]
    if not matches:
        raise CommandError(f"Manual job named {identifier!r} was not found in the head pipeline.")
    if len(matches) > 1:
        raise CommandError(
            f"Manual job name {identifier!r} is ambiguous. Matching ids: {', '.join(str(job['id']) for job in matches)}"
        )
    return resolved, head_pipeline, matches[0]


def require_glab() -> None:
    if shutil.which("glab") is None:
        raise CommandError("glab is not installed or not in PATH.")


def ensure_glab_auth(hostname: str) -> None:
    require_glab()
    result = subprocess.run(
        ["glab", "auth", "status", "--hostname", hostname],
        capture_output=True,
        text=True,
    )
    if result.returncode == 0:
        print(f"glab authentication is configured for {hostname}.", file=sys.stderr)
        return
    raise CommandError(
        f"glab authentication is missing for {hostname}.\n"
        f"Bootstrap it with: gmr auth bootstrap {hostname}"
    )


def bootstrap_glab_auth(target: str) -> None:
    require_glab()
    host_info = parse_target_host(target)
    hostname = host_info["hostname"]

    git_protocol = os.environ.get("GITLAB_GIT_PROTOCOL", "ssh")
    api_host = os.environ.get("GITLAB_API_HOST", "")
    api_protocol = os.environ.get("GITLAB_API_PROTOCOL", "")

    if not api_protocol and "://" in target:
        parsed = urllib.parse.urlparse(target)
        if parsed.scheme:
            api_protocol = parsed.scheme

    if not api_host and host_info["authority"]:
        api_host = host_info["authority"]

    if sys.stdin.isatty():
        token = getpass.getpass(f"GitLab PAT for {hostname}: ")
    else:
        token = sys.stdin.read().strip()
    if not token:
        raise CommandError("No token provided on stdin or prompt.")

    cmd = [
        "glab", "auth", "login",
        "--hostname", hostname,
        "--git-protocol", git_protocol,
        "--use-keyring",
        "--stdin",
    ]
    if api_host:
        cmd += ["--api-host", api_host]
    if api_protocol:
        cmd += ["--api-protocol", api_protocol]

    run_command(cmd, input_text=token)
    run_command(["glab", "auth", "status", "--hostname", hostname], capture_output=False)


def command_auth_ensure(args: argparse.Namespace) -> None:
    hostname = parse_target_hostname(args.target)
    ensure_glab_auth(hostname)


def command_auth_ensure_mr(args: argparse.Namespace) -> None:
    ctx = resolve_mr_target(args.target, args.repo, args.hostname)
    ensure_glab_auth(ctx["hostname"])


def command_auth_bootstrap(args: argparse.Namespace) -> None:
    bootstrap_glab_auth(args.target)


def command_mr_create(args: argparse.Namespace) -> None:
    ctx = resolve_repo_target(args.repo, args.hostname)
    source_branch = args.source_branch or infer_current_branch()
    if not source_branch:
        raise CommandError(
            "Source branch is required when it cannot be inferred from the current checkout."
        )
    if not args.fill and not args.title:
        raise CommandError("Use --fill or provide --title for non-interactive MR creation.")

    command = [
        "glab",
        "mr",
        "create",
        "-R",
        ctx["repo"],
        "-s",
        source_branch,
        "--yes",
    ]

    if args.fill:
        command.append("--fill")
        if args.fill_commit_body:
            command.append("--fill-commit-body")
    else:
        command += ["-t", args.title, "-d", args.description or ""]

    if args.target_branch:
        command += ["-b", args.target_branch]
    if args.draft:
        command.append("--draft")
    for label in args.label or []:
        command += ["-l", label]
    for reviewer in args.reviewer or []:
        command += ["--reviewer", reviewer]
    for assignee in args.assignee or []:
        command += ["-a", assignee]

    output = run_command(command, env=glab_cli_env(ctx["hostname"]))
    mr_url = extract_mr_web_url(output)
    if not mr_url:
        raise CommandError("Could not determine the created merge request URL from glab output.")
    created_ctx = resolve_mr_target(mr_url, ctx["repo"], ctx["hostname"])
    created_mr = get_mr(created_ctx)
    print_json(
        {
            "action": "create",
            "target": created_ctx,
            "source_branch": source_branch,
            "target_branch": args.target_branch,
            "draft": args.draft,
            "fill": args.fill,
            "mr_url": mr_url,
            "mr": select_mr_fields(created_mr),
            "output": output.strip() or None,
        }
    )


def command_mr_list(args: argparse.Namespace) -> None:
    ctx = resolve_repo_target(args.repo, args.hostname)
    current_user_info: dict[str, Any] | None = None

    if args.draft and args.not_draft:
        raise CommandError("Cannot combine --draft and --not-draft.")

    author, author_candidates, current_user_info = resolve_user_filter(
        args.author,
        ctx["hostname"],
        current_user_info,
    )
    assignee, assignee_candidates, current_user_info = resolve_user_filter(
        args.assignee,
        ctx["hostname"],
        current_user_info,
    )
    reviewer, reviewer_candidates, current_user_info = resolve_user_filter(
        args.reviewer,
        ctx["hostname"],
        current_user_info,
    )

    if args.mine:
        current_user_info = current_user_info or resolve_current_user(ctx["hostname"])
        current_user = current_user_info["username"]
        current_user_candidates = current_user_info["candidates"]
        if args.mine_role == "author":
            if author:
                raise CommandError("Cannot combine --mine with --author.")
            author = current_user
            author_candidates = current_user_candidates
        elif args.mine_role == "assignee":
            if assignee:
                raise CommandError("Cannot combine --mine with --assignee.")
            assignee = current_user
            assignee_candidates = current_user_candidates
        elif args.mine_role == "reviewer":
            if reviewer:
                raise CommandError("Cannot combine --mine with --reviewer.")
            reviewer = current_user
            reviewer_candidates = current_user_candidates

    command = [
        "glab",
        "mr",
        "list",
        "-R",
        ctx["repo"],
        "-F",
        "json",
        "-P",
        str(args.per_page),
    ]

    if args.page != 1:
        command += ["-p", str(args.page)]

    if args.state == "closed":
        command.append("--closed")
    elif args.state == "merged":
        command.append("--merged")
    elif args.state == "all":
        command.append("--all")

    if author:
        command += ["--author", author]
    if assignee:
        command += ["--assignee", assignee]
    if reviewer:
        command += ["--reviewer", reviewer]
    if args.source_branch:
        command += ["--source-branch", args.source_branch]
    if args.target_branch:
        command += ["--target-branch", args.target_branch]
    if args.search:
        command += ["--search", args.search]
    for label in args.label or []:
        command += ["--label", label]
    if args.draft:
        command.append("--draft")
    if args.not_draft:
        command.append("--not-draft")

    output = run_command(command, env=glab_cli_env(ctx["hostname"]))
    merge_requests = post_filter_merge_requests(
        json.loads(output),
        author_candidates=author_candidates,
        assignee_candidates=assignee_candidates,
        reviewer_candidates=reviewer_candidates,
        draft=args.draft,
        not_draft=args.not_draft,
    )

    print_json(
        {
            "target": ctx,
            "filters": {
                "state": args.state,
                "author": author,
                "assignee": assignee,
                "reviewer": reviewer,
                "mine": args.mine,
                "mine_role": args.mine_role if args.mine else None,
                "current_user": current_user_info["username"] if current_user_info else None,
                "current_user_candidates": current_user_info["candidates"] if current_user_info else [],
                "draft": args.draft,
                "not_draft": args.not_draft,
                "source_branch": args.source_branch,
                "target_branch": args.target_branch,
                "search": args.search,
                "labels": args.label or [],
                "page": args.page,
                "per_page": args.per_page,
            },
            "count": len(merge_requests),
            "items": [select_mr_list_fields(mr) for mr in merge_requests],
        }
    )


def command_mr_status(args: argparse.Namespace) -> None:
    ctx = resolve_mr_target(args.target, args.repo, args.hostname)
    print_json(gather_status(ctx, trace_lines=args.trace_lines))


def command_mr_manual_jobs(args: argparse.Namespace) -> None:
    ctx = resolve_mr_target(args.target, args.repo, args.hostname)
    status_payload = gather_status(ctx, trace_lines=8)
    output = {
        "target": status_payload["target"],
        "mr": status_payload["mr"],
        "head_pipeline": status_payload["head_pipeline"],
        "manual_jobs": status_payload["manual_jobs"],
    }
    print_json(output)


def command_mr_run_manual(args: argparse.Namespace) -> None:
    ctx, head_pipeline, job = find_manual_job(
        args.mr,
        args.repo,
        args.hostname,
        args.job,
    )
    payload = glab_json(
        ctx["hostname"],
        f"projects/{ctx['repo_encoded']}/jobs/{job['id']}/play",
        method="POST",
    )
    print_json(
        {
            "target": ctx,
            "head_pipeline": head_pipeline,
            "triggered_job": select_job_fields(payload),
        }
    )


def command_mr_approve(args: argparse.Namespace) -> None:
    ctx = resolve_mr_target(args.target, args.repo, args.hostname)
    mr = get_mr(ctx)
    sha = args.sha or mr.get("sha")
    if not sha:
        raise CommandError("Could not determine the merge request HEAD SHA for approval.")

    output = run_command(
        [
            "glab",
            "mr",
            "approve",
            ctx["iid"],
            "-R",
            ctx["repo"],
            "-s",
            sha,
        ],
        env=glab_cli_env(ctx["hostname"]),
    )
    print_json(
        {
            "action": "approve",
            "target": ctx,
            "sha": sha,
            "output": output.strip() or None,
        }
    )


def command_mr_merge(args: argparse.Namespace) -> None:
    ctx = resolve_mr_target(args.target, args.repo, args.hostname)
    mr = get_mr(ctx)
    sha = args.sha or mr.get("sha")
    if not sha:
        raise CommandError("Could not determine the merge request HEAD SHA for merge.")
    if mr.get("draft"):
        raise CommandError("Refusing to merge a draft merge request.")

    head_pipeline = mr.get("head_pipeline") or {}
    pipeline_status = head_pipeline.get("status")
    if pipeline_status == "failed":
        raise CommandError("Refusing to merge while the head pipeline is failed.")
    if pipeline_status in {"running", "pending", "created", "preparing", "waiting_for_resource"} and not args.auto_merge:
        raise CommandError(
            "Head pipeline is not finished yet. Re-run with --auto-merge or wait for a green pipeline."
        )

    command = [
        "glab",
        "mr",
        "merge",
        ctx["iid"],
        "-R",
        ctx["repo"],
        "--sha",
        sha,
        "--yes",
    ]
    if not args.keep_source_branch:
        command.append("--remove-source-branch")
    if args.rebase:
        command.append("--rebase")
    if args.squash:
        command.append("--squash")
    if args.auto_merge:
        command.append("--auto-merge")
    if args.message:
        command += ["--message", args.message]

    output = run_command(command, env=glab_cli_env(ctx["hostname"]))
    print_json(
        {
            "action": "merge",
            "target": ctx,
            "sha": sha,
            "auto_merge": args.auto_merge,
            "removed_source_branch": not args.keep_source_branch,
            "output": output.strip() or None,
        }
    )


def command_mr_review_context(args: argparse.Namespace) -> None:
    ctx = resolve_mr_target(args.target, args.repo, args.hostname)
    status_payload = gather_status(ctx, trace_lines=12)
    changed_files, change_meta = get_review_changes(ctx)
    unresolved_discussions = get_unresolved_discussions(ctx, include_bots=args.include_bots)
    print_json(
        {
            "target": status_payload["target"],
            "mr": status_payload["mr"],
            "head_pipeline": status_payload["head_pipeline"],
            "failed_jobs": status_payload["failed_jobs"],
            "unresolved_discussions": unresolved_discussions,
            "changed_files_count": change_meta["changes_count"],
            "changed_files_overflow": change_meta["overflow"],
            "changed_files": changed_files,
        }
    )


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="gmr")
    subparsers = parser.add_subparsers(dest="top_command", required=True)

    auth_parser = subparsers.add_parser("auth")
    auth_subparsers = auth_parser.add_subparsers(dest="auth_command", required=True)

    auth_ensure = auth_subparsers.add_parser("ensure")
    auth_ensure.add_argument("target")
    auth_ensure.set_defaults(func=command_auth_ensure)

    auth_ensure_mr = auth_subparsers.add_parser("ensure-mr")
    auth_ensure_mr.add_argument("target", help="MR URL or IID.")
    auth_ensure_mr.add_argument("--repo")
    auth_ensure_mr.add_argument("--hostname")
    auth_ensure_mr.set_defaults(func=command_auth_ensure_mr)

    auth_bootstrap = auth_subparsers.add_parser("bootstrap")
    auth_bootstrap.add_argument("target")
    auth_bootstrap.set_defaults(func=command_auth_bootstrap)

    mr_parser = subparsers.add_parser("mr")
    mr_subparsers = mr_parser.add_subparsers(dest="mr_command", required=True)

    create_parser = mr_subparsers.add_parser("create")
    create_parser.add_argument("--repo")
    create_parser.add_argument("--hostname")
    create_parser.add_argument("--source-branch")
    create_parser.add_argument("--target-branch")
    create_parser.add_argument("--title")
    create_parser.add_argument("--description")
    create_parser.add_argument("--fill", action="store_true")
    create_parser.add_argument("--fill-commit-body", action="store_true")
    create_parser.add_argument("--draft", action="store_true")
    create_parser.add_argument("-l", "--label", action="append")
    create_parser.add_argument("--reviewer", action="append")
    create_parser.add_argument("-a", "--assignee", action="append")
    create_parser.set_defaults(func=command_mr_create)

    list_parser = mr_subparsers.add_parser("list")
    list_parser.add_argument("--repo")
    list_parser.add_argument("--hostname")
    list_parser.add_argument(
        "--state",
        choices=["opened", "closed", "merged", "all"],
        default="opened",
    )
    list_parser.add_argument("--author")
    list_parser.add_argument("--assignee")
    list_parser.add_argument("--reviewer")
    list_parser.add_argument("--mine", action="store_true")
    list_parser.add_argument(
        "--mine-role",
        choices=["author", "assignee", "reviewer"],
        default="author",
    )
    list_parser.add_argument("--draft", action="store_true")
    list_parser.add_argument("--not-draft", action="store_true")
    list_parser.add_argument("--source-branch")
    list_parser.add_argument("--target-branch")
    list_parser.add_argument("--search")
    list_parser.add_argument("-l", "--label", action="append")
    list_parser.add_argument("-p", "--page", type=int, default=1)
    list_parser.add_argument("-P", "--per-page", type=int, default=30)
    list_parser.set_defaults(func=command_mr_list)

    status_parser = mr_subparsers.add_parser("status")
    status_parser.add_argument("target")
    status_parser.add_argument("--repo")
    status_parser.add_argument("--hostname")
    status_parser.add_argument("--trace-lines", type=int, default=12)
    status_parser.set_defaults(func=command_mr_status)

    manual_jobs_parser = mr_subparsers.add_parser("manual-jobs")
    manual_jobs_parser.add_argument("target")
    manual_jobs_parser.add_argument("--repo")
    manual_jobs_parser.add_argument("--hostname")
    manual_jobs_parser.set_defaults(func=command_mr_manual_jobs)

    run_manual_parser = mr_subparsers.add_parser("run-manual")
    run_manual_parser.add_argument("job", help="Manual job id or exact job name.")
    run_manual_parser.add_argument("--mr", required=True, help="MR URL or IID.")
    run_manual_parser.add_argument("--repo")
    run_manual_parser.add_argument("--hostname")
    run_manual_parser.set_defaults(func=command_mr_run_manual)

    approve_parser = mr_subparsers.add_parser("approve")
    approve_parser.add_argument("target", help="MR URL or IID.")
    approve_parser.add_argument("--repo")
    approve_parser.add_argument("--hostname")
    approve_parser.add_argument("--sha")
    approve_parser.set_defaults(func=command_mr_approve)

    merge_parser = mr_subparsers.add_parser("merge")
    merge_parser.add_argument("target", help="MR URL or IID.")
    merge_parser.add_argument("--repo")
    merge_parser.add_argument("--hostname")
    merge_parser.add_argument("--sha")
    merge_parser.add_argument("--auto-merge", action="store_true")
    merge_parser.add_argument("--keep-source-branch", action="store_true")
    merge_parser.add_argument("--rebase", action="store_true")
    merge_parser.add_argument("--squash", action="store_true")
    merge_parser.add_argument("--message")
    merge_parser.set_defaults(func=command_mr_merge)

    review_parser = mr_subparsers.add_parser("review-context")
    review_parser.add_argument("target")
    review_parser.add_argument("--repo")
    review_parser.add_argument("--hostname")
    review_parser.add_argument("--include-bots", action="store_true")
    review_parser.set_defaults(func=command_mr_review_context)

    return parser


def main() -> int:
    parser = build_parser()
    args = parser.parse_args()
    try:
        args.func(args)
    except KeyboardInterrupt:
        return 130
    except (CommandError, subprocess.CalledProcessError) as exc:
        print(str(exc), file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
